version: '3.5'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres
    ports:
      - 5432:5432


  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    env_file:
      - .env

networks:
  nestdev:
    external: true